apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-staging-sth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/erangaeb/kube-manifests.git
    targetRevision: cad3b5c926e38764a38ed16e8104fad5fd59bbe9
    path: staging-sth
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-staging-sth
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
