apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/erangaeb/kube-manifests.git
    targetRevision: b25a22d4fa800affcfaf43cba912229cec48eb58
    path: test
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-test
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
