apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/erangaeb/kube-manifests.git
    targetRevision: 01bbf715160c8659477f8bddb920391eda939c38
    path: test
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-test
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
